
server:
  port: 8282

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa-study
    username : root
    password: mariadb
    driver-class-name : org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl ??? ??? ????...
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? ??? ??
    database: mysql

logging:
  level:
    root: info
    com:
      spring:
        jpa_study: debug
    org:
      hibernate:
        SQL: debug